### ISSUE TITLE
error: A BlockEntity type mcjty.rftoolsbuilder.modules.shield.blocks.ShieldingTileEntity has thrown an exception trying to write state.

### ISSUE THREAD

**Issue by Lolothepro** [McJtyMods/RFToolsBuilder#136]
```
[net.minecraft.world.level.chunk.LevelChunk/]: A BlockEntity type mcjty.rftoolsbuilder.modules.shield.blocks.ShieldingTileEntity has thrown an exception trying to write state. It will not persist, Report this to the mod author
java.lang.NullPointerException: Cannot invoke "net.minecraft.core.BlockPos.m_123341_()" because "this.shieldProjector" is null
	at mcjty.rftoolsbuilder.modules.shield.blocks.ShieldingTileEntity.m_183515_(ShieldingTileEntity.java:116) ~[rftoolsbuilder-1.20-6.0.0.jar%23488!/:1.20-6.0.0]
	at net.minecraft.world.level.block.entity.BlockEntity.m_187482_(BlockEntity.java:77) ~[client-1.20.1-20230612.114412-srg.jar%23544!/:?]
	at net.minecraft.world.level.block.entity.BlockEntity.m_187480_(BlockEntity.java:64) ~[client-1.20.1-20230612.114412-srg.jar%23544!/:?]
	at net.minecraft.world.level.chunk.LevelChunk.m_8051_(LevelChunk.java:376) ~[client-1.20.1-20230612.114412-srg.jar%23544!/:?]
	at net.minecraft.world.level.chunk.storage.ChunkSerializer.m_63454_(ChunkSerializer.java:324) ~[client-1.20.1-20230612.114412-srg.jar%23544!/:?]
	at net.minecraft.server.level.ChunkMap.m_140258_(ChunkMap.java:834) ~[client-1.20.1-20230612.114412-srg.jar%23544!/:?]
	at net.minecraft.server.level.ChunkMap.m_198874_(ChunkMap.java:801) ~[client-1.20.1-20230612.114412-srg.jar%23544!/:?]
	at net.minecraft.server.level.ChunkMap.m_140353_(ChunkMap.java:490) ~[client-1.20.1-20230612.114412-srg.jar%23544!/:?]
	at net.minecraft.server.level.ChunkMap.m_140280_(ChunkMap.java:454) ~[client-1.20.1-20230612.114412-srg.jar%23544!/:?]
	at net.minecraft.server.level.ServerChunkCache.m_201698_(ServerChunkCache.java:320) ~[client-1.20.1-20230612.114412-srg.jar%23544!/:?]
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:305) ~[client-1.20.1-20230612.114412-srg.jar%23544!/:?]
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:893) ~[client-1.20.1-20230612.114412-srg.jar%23544!/:?]
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814) ~[client-1.20.1-20230612.114412-srg.jar%23544!/:?]
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:89) ~[client-1.20.1-20230612.114412-srg.jar%23544!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[client-1.20.1-20230612.114412-srg.jar%23544!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[client-1.20.1-20230612.114412-srg.jar%23544!/:?]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

**Comment by McJty** [comment]
Please. A little bit more information. Like version of the mod. What you are doing and do on. I can't do anything with vague reports like this

**Comment by Lolothepro** [comment]
> Please. A little bit more information. Like version of the mod. What you are doing and do on. I can't do anything with vague reports like this

Minecraft 1.20.1
RFToolsBuilder 6.0.0
This error occurs in debug worlds

**Comment by McJty** [comment]
Yes but how do you get this error? What do you do in game?

**Comment by McJty** [comment]
Also 6.0.0 is old. you should update

**Comment by Lolothepro** [comment]
> Yes but how do you get this error? What do you do in game?

Nothing, just generate chunks in the debug world

**Comment by McJty** [comment]
Well that's not possible because shields don't generate with the world. They are player placed

**Comment by Lolothepro** [comment]
> Well that's not possible because shields don't generate with the world. They are player placed

https://minecraft.wiki/w/Debug_mode

**Comment by McJty** [comment]
Ah ok. Have to check
