### ISSUE TITLE
Server Crash Whilst Quarrying

### ISSUE THREAD

**Issue by ChloeDawn** [McJtyMods/RFToolsBuilder#26]
**Mod version:** 1.15-2.1.3-beta

It seems Mojang call a client method from an override of `Block#getItem`, and the override isn't stripped. Unsure how that works.

```
---- Minecraft Crash Report ----
// Why is it breaking :(

Time: 7/17/20 2:37 AM
Description: Ticking block entity

java.lang.NoSuchMethodError: net.minecraft.block.BannerBlock.func_196287_a(Lnet/minecraft/item/DyeColor;)Lnet/minecraft/block/Block;
	at net.minecraft.tileentity.BannerTileEntity.func_190615_l(BannerTileEntity.java:162) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.block.AbstractBannerBlock.func_185473_a(AbstractBannerBlock.java:41) ~[?:?] {re:classloading}
	at mcjty.rftoolsbuilder.modules.builder.blocks.BuilderTileEntity.commonQuarryBlock(BuilderTileEntity.java:1227) ~[?:1.15-2.1.3-beta] {re:classloading}
	at mcjty.rftoolsbuilder.modules.builder.blocks.BuilderTileEntity.silkQuarryBlock(BuilderTileEntity.java:1154) ~[?:1.15-2.1.3-beta] {re:classloading}
	at mcjty.rftoolsbuilder.modules.builder.items.ShapeCardType.handleSingleBlock(ShapeCardType.java:200) ~[?:1.15-2.1.3-beta] {re:classloading}
	at mcjty.rftoolsbuilder.modules.builder.blocks.BuilderTileEntity.handleSingleBlock(BuilderTileEntity.java:1068) ~[?:1.15-2.1.3-beta] {re:classloading}
	at mcjty.rftoolsbuilder.modules.builder.blocks.BuilderTileEntity.handleBlockShaped(BuilderTileEntity.java:1009) ~[?:1.15-2.1.3-beta] {re:classloading}
	at mcjty.rftoolsbuilder.modules.builder.blocks.BuilderTileEntity.checkStateServerShaped(BuilderTileEntity.java:736) ~[?:1.15-2.1.3-beta] {re:classloading}
	at mcjty.rftoolsbuilder.modules.builder.blocks.BuilderTileEntity.checkStateServer(BuilderTileEntity.java:774) ~[?:1.15-2.1.3-beta] {re:classloading}
	at mcjty.rftoolsbuilder.modules.builder.blocks.BuilderTileEntity.func_73660_a(BuilderTileEntity.java:748) ~[?:1.15-2.1.3-beta] {re:classloading}
	at net.minecraft.world.World.func_217391_K(World.java:473) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:368) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:quark:change-sleeping-player-count,xf:fml:quark:add-rave-hook,xf:fml:immersiveengineering:IE block update callback,pl:mixin:APP:assets/fruittrees/fruittrees.mixins.json:MixinServerWorld,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:849) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:330) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:784) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:637) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.tileentity.BannerTileEntity.func_190615_l(BannerTileEntity.java:162)
	at net.minecraft.block.AbstractBannerBlock.func_185473_a(AbstractBannerBlock.java:41)
	at mcjty.rftoolsbuilder.modules.builder.blocks.BuilderTileEntity.commonQuarryBlock(BuilderTileEntity.java:1227)
	at mcjty.rftoolsbuilder.modules.builder.blocks.BuilderTileEntity.silkQuarryBlock(BuilderTileEntity.java:1154)
	at mcjty.rftoolsbuilder.modules.builder.items.ShapeCardType.handleSingleBlock(ShapeCardType.java:200)
	at mcjty.rftoolsbuilder.modules.builder.blocks.BuilderTileEntity.handleSingleBlock(BuilderTileEntity.java:1068)
	at mcjty.rftoolsbuilder.modules.builder.blocks.BuilderTileEntity.handleBlockShaped(BuilderTileEntity.java:1009)
	at mcjty.rftoolsbuilder.modules.builder.blocks.BuilderTileEntity.checkStateServerShaped(BuilderTileEntity.java:736)
	at mcjty.rftoolsbuilder.modules.builder.blocks.BuilderTileEntity.checkStateServer(BuilderTileEntity.java:774)
	at mcjty.rftoolsbuilder.modules.builder.blocks.BuilderTileEntity.func_73660_a(BuilderTileEntity.java:748)

-- Block entity being ticked --
Details:
	Name: rftoolsbuilder:builder // mcjty.rftoolsbuilder.modules.builder.blocks.BuilderTileEntity
	Block: Block{rftoolsbuilder:builder}[facing=east]
	Block location: World: (-3997,106,-3955), Chunk: (at 3,6,13 in -250,-248; contains blocks -4000,0,-3968 to -3985,255,-3953), Region: (-8,-8; contains chunks -256,-256 to -225,-225, blocks -4096,0,-4096 to -3585,255,-3585)
	Block: Block{rftoolsbuilder:builder}[facing=east]
	Block location: World: (-3997,106,-3955), Chunk: (at 3,6,13 in -250,-248; contains blocks -4000,0,-3968 to -3985,255,-3953), Region: (-8,-8; contains chunks -256,-256 to -225,-225, blocks -4096,0,-4096 to -3585,255,-3585)
Stacktrace:
	at net.minecraft.world.World.func_217391_K(World.java:473)
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:368)

-- Affected level --
Details:
	All players: 0 total; []
	Chunk stats: ServerChunkCache: 6106
	Level dimension: DimensionType{minecraft:overworld}
	Level name: world
	Level seed: -8216558377797429175
	Level generator: ID 07 - biomesoplenty, ver 0. Features enabled: true
	Level generator options: {}
	Level spawn location: World: (-32,68,96), Chunk: (at 0,4,0 in -2,6; contains blocks -32,0,96 to -17,255,111), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 37846057 game time, 44023038 day time
	Known server brands: forge
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 38795 (now: false), thunder time: 13883 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:849)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:330)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:784)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:637)
	at java.lang.Thread.run(Thread.java:748)

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Linux (amd64) version 4.15.0-106-generic
	Java Version: 1.8.0_212, AdoptOpenJDK
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), AdoptOpenJDK
	Memory: 637285816 bytes (607 MB) / 2524446720 bytes (2407 MB) up to 2863661056 bytes (2731 MB)
	CPUs: 3
	JVM Flags: 6 total; -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:MaxRAMFraction=2 -Xms1024M -Xmx3072M -XX:-UsePerfData
	ModLauncher: 5.1.0+69+master.79f13f7
	ModLauncher launch target: fmlserver
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-2.2.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.15.2-31.2.30.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.15.2-31.2.30.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.1.3-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.15.2-31.2.30.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.15.2-31.2.30.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.15.2-31.2.30.jar fml TRANSFORMATIONSERVICE 
		/MixinBootstrap-1.0.3.jar mixinbootstrap TRANSFORMATIONSERVICE 
		/MixinBootstrap-1.0.3.jar mixin PLUGINSERVICE 
		/MixinBootstrap-1.0.3.jar mixinbootstrap PLUGINSERVICE 
	FML: 31.2
	Forge: net.minecraftforge:31.2.30
	FML Language Providers: 
		javafml@31.2
		minecraft@1
		kotlinfml@1.5.2
	Mod List: 
		NetherPortalFix_1.15.2-6.0.2.jar NetherPortalFix {netherportalfix@6.0.2 DONE}
		aiotbotania-1.15.2-1.2.3.jar AIOT Botania {aiotbotania@1.2.3 DONE}
		scenic-1.15.2-1.0.0.jar Scenic {scenic@1.15.2-1.0.0 DONE}
		refinedpipes-0.4.2.jar Refined Pipes {refinedpipes@0.4.2 DONE}
		DoggyTalents-1.15.2-1.15.2.3.jar Doggy Talents {doggytalents@1.15.2.3 DONE}
		mcw-windows-1.0.1-mc1.15.2_1.15.1.jar Macaw's Windows {mcwwindows@1.0.1 DONE}
		SilentMechanisms-1.15.2-0.7.6+57.jar Silent's Mechanisms {silents_mechanisms@0.7.6+57 DONE}
		essentials-1.15.2-2.7.3.jar Essentials {essentials@1.15.2-2.7.3 DONE}
		TerraForged-1.15.2-0.0.15.jar TerraForged {terraforged@0.0.15 DONE}
		XaerosWorldMap_1.7.0_Forge_1.15.2.jar Xaero's World Map {xaeroworldmap@1.7.0 DONE}
		CookingForBlockheads_1.15.2-8.0.3.jar Cooking for Blockheads {cookingforblockheads@8.0.3 DONE}
		Placebo-1.15.2-3.1.0.jar Placebo {placebo@3.1.0 DONE}
		Powah-1.15.2-1.1.14.jar Powah {powah@1.1.14 DONE}
		Bookshelf-1.15.2-5.6.40.jar Bookshelf {bookshelf@5.6.40 DONE}
		u_team_core-1.15.2-3.0.0.160.jar U Team Core {uteamcore@3.0.0.160 DONE}
		randompatches-1.15.2-1.22.0.0.jar RandomPatches {randompatches@1.15.2-1.22.0.0 DONE}
		DarkUtilities-1.15.2-3.0.7.jar Dark Utilities {darkutils@3.0.7 DONE}
		Apotheosis-1.15.2-3.2.1.jar Apotheosis {apotheosis@3.2.1 DONE}
		ProgressiveBosses-2.1.5-mc1.15.2.jar Progressive Bosses {progressivebosses@2.1.5-mc1.15.2 DONE}
		mcw-doors-1.0.0-mc1.15.2.jar Macaw's Doors {mcwdoors@1.0.0 DONE}
		MekanismGenerators-1.15.2-9.10.9.422.jar Mekanism: Generators {mekanismgenerators@9.10.9 DONE}
		absentbydesign-1.15.2-1.1.0.jar Absent By Design Mod {absentbydesign@1.15.2-1.1.0 DONE}
		refinedstorage-1.8.6.jar Refined Storage {refinedstorage@1.8.6 DONE}
		structure-gel-api-1.15.2-1.1.0.jar Structure Gel API {structure_gel@1.1.0 DONE}
		PackMenu-1.15.2-1.2.4.jar Pack Menu {packmenu@1.2.4 DONE}
		mcw-bridges-1.0.4fix-mc1.15.2.jar Macaw's Bridges {mcwbridges@1.0.4 DONE}
		lightestlamp-3.4.3.jar Lightest Lamps {lightestlamp@3.4.3 DONE}
		industrial-foregoing-1.15.2-2.3.3-e356e61.jar Industrial Foregoing {industrialforegoing@2.3.3 DONE}
		useful_backpacks-1.15.2-1.10.1.66.jar Useful Backpacks {usefulbackpacks@1.10.1.66 DONE}
		torchmaster-2.2.0.jar Torchmaster {torchmaster@2.2.0 DONE}
		BiomesOPlenty-1.15.2-10.0.0.366-universal.jar Biomes O' Plenty {biomesoplenty@1.15.2-10.0.0.366 DONE}
		phosphor-forge-mc1.15.2-0.5.2+build.4.jar Phosphor {phosphor@0.5.2+build.4 DONE}
		MekanismAdditions-1.15.2-9.10.9.422.jar Mekanism: Additions {mekanismadditions@9.10.9 DONE}
		valhelsia_structures-15.0.3a.jar Valhelsia Structures {valhelsia_structures@15.0.3a DONE}
		Lollipop-1.15.2-1.0.15.jar Lollipop {lollipop@1.0.15 DONE}
		toughnessbar-5.0.jar Toughness Bar {toughnessbar@5.0 DONE}
		SilentGear-1.15.2-1.8.2+109.jar Silent Gear {silentgear@1.8.2+109 DONE}
		simplefarming-1.15.2-1.2.9.jar Simple Farming {simplefarming@1.15.2-1.2.9 DONE}
		SolarFluxReborn-1.15.2-15.0.0.jar Solar Flux Reborn {solarflux@15.0.0 DONE}
		curios-FORGE-1.15.2-2.0.2.4.jar Curios API {curios@FORGE-1.15.2-2.0.2.4 DONE}
		Botania-r1.15-387.jar Botania {botania@r1.15-387 DONE}
		Patchouli-1.15.2-1.2-34.jar Patchouli {patchouli@1.15.2-1.2-34 DONE}
		extlights-2.1.jar Extended Lights {extlights@2.1 DONE}
		config-2-3.0.jar Cloth Config v2 API {cloth-config2@3.0 DONE}
		libnonymous-1.15.2-1.1.1.5.jar Libnonymous {libnonymous@1.1.1.5 DONE}
		elevatorid-1.15.2-1.7.1.jar Elevator Mod {elevatorid@1.15.2-1.7.1 DONE}
		MekanismTools-1.15.2-9.10.9.422.jar Mekanism: Tools {mekanismtools@9.10.9 DONE}
		mcw-roofs-1.0.2-mc1.15.2_1.15.1.jar Macaw's Roofs {mcwroofs@1.0.2 DONE}
		furniture-7.0.0-pre16-1.15.1.jar MrCrayfish's Furniture Mod {cfm@7.0.0-pre16 DONE}
		curiouselytra-FORGE-1.15.2-2.0.jar Curious Elytra {curiouselytra@FORGE-1.15.2-2.0 DONE}
		AI-Improvements-1.15.2-0.3.0.jar AI-Improvements {aiimprovements@0.3.0 DONE}
		mcw-furniture-1.0.1-mc1.15.1 1.15.2.jar Macaw's Furnitures {mcwfurnitures@1.0.1 DONE}
		bwncr-1.15.1-3.6.13.jar Bad Wither No Cookie Reloaded {bwncr@1.15.1-3.6.13 DONE}
		FastLeafDecay-v22.jar FastLeafDecay {fastleafdecay@v22 DONE}
		CodeChickenLib-1.15.2-3.3.0.373-universal.jar CodeChicken Lib {codechickenlib@3.3.0.373 DONE}
		ServerTabInfo-1.15.2-1.2.7.jar Server Tab Info {servertabinfo@1.2.7 DONE}
		leavesdecayonotherleaves-1.1.jar Leaves Decay on other Leaves {leavesdecayonotherleaves@1.1 DONE}
		BetterAdvancements-1.15.2-0.1.0.99.jar Better Advancements {betteradvancements@0.1.0.99 DONE}
		QuarkOddities-1.15.2.jar Quark Oddities {quarkoddities@1.15.2 DONE}
		inventorysorter-1.15.2-17.0.0.jar Simple Inventory Sorter {inventorysorter@17.0.0 DONE}
		TrashSlot_1.15.2-11.0.0.jar TrashSlot {trashslot@11.0.0 DONE}
		torchslabmod-1.15.2_v1.7.0.jar Torch Slab Mod {torchslabmod@1.7.0 DONE}
		mining-helmet-1.15.2-1.0.8.jar Mining Helmet {mining_helmet@1.0.8 DONE}
		jei-1.15.2-6.0.2.12.jar Just Enough Items {jei@6.0.2.12 DONE}
		Druidcraft-1.15-0.4.21.jar Druidcraft {druidcraft@0.4.21 DONE}
		AttributeFix-1.15.2-7.0.2.jar AttributeFix {attributefix@7.0.2 DONE}
		the-conjurer-1.15.2-1.0.6.jar The Conjurer {conjurer_illager@1.0.6 DONE}
		Abnormals-Core-1.15.2-1.0.6.jar Abnormals Core {abnormals_core@1.0.6 DONE}
		Buzzier-Bees-1.15.2-1.5.2.jar Buzzier Bees {buzzierbees@1.5.2 DONE}
		Mekanism-1.15.2-9.10.9.422.jar Mekanism {mekanism@9.10.9 DONE}
		caelus-FORGE-1.15.2-2.0-beta3.jar Caelus API {caelus@FORGE-1.15.2-2.0-beta3 DONE}
		Upgrade-Aquatic-1.15.2-1.7.0.jar Upgrade Aquatic {upgrade_aquatic@1.7.0 DONE}
		reap-1.12.5.jar Reap Mod {reap@1.12.5 DONE}
		create-mc1.15.2_v0.2.4d.jar Create {create@mc1.15.2_v0.2.4d DONE}
		Waystones_1.15.2-6.0.2.jar Waystones {waystones@6.0.2 DONE}
		Clumps-5.0.2.jar Clumps {clumps@5.0.2 DONE}
		comforts-FORGE-1.15.2-2.0.0.3.jar Comforts {comforts@FORGE-1.15.2-2.0.0.3 DONE}
		NaturesCompass-1.15.2-1.8.5.jar Nature's Compass {naturescompass@1.15.2-1.8.5 DONE}
		FruitTrees-1.15.2-1.5.0.jar Fruit Trees {fruittrees@1.5.0 DONE}
		Kiwi-1.15.2-2.7.2.jar Kiwi {kiwi@2.7.2 DONE}
		SimpleStorageNetwork-1.15.2-1.0.1.jar Simple Storage Network {storagenetwork@1.15.2-1.0.1 DONE}
		SereneSeasons-1.15.2-3.0.0.72-universal.jar Serene Seasons {sereneseasons@1.15.2-3.0.0.72 DONE}
		decorative_blocks-6d.jar Decorative Blocks {decorative_blocks@1.6 DONE}
		BotanyPots-1.15.2-2.0.25.jar BotanyPots {botanypots@2.0.25 DONE}
		curioofundying-FORGE-1.15.2-3.0.jar Curio of Undying {curioofundying@FORGE-1.15.2-3.0 DONE}
		snowundertrees-1.15.2-v1.1.1.jar Snow Under Trees {snowundertrees@v1.1.1 DONE}
		BonsaiTrees-2.1.2.6.jar Bonsai Trees 2 {bonsaitrees2@2.1.2.6 DONE}
		mcjtylib-1.15-4.1.1-beta.jar McJtyLib {mcjtylib@1.15-4.1.1-beta DONE}
		rftoolsbase-1.15-1.1.1-beta.jar RFToolsBase {rftoolsbase@1.15-1.1.1-beta DONE}
		xnet-1.15-2.1.5-beta.jar XNet {xnet@1.15-2.1.5-beta DONE}
		rftoolsstorage-1.15-1.1.4-beta.jar RFToolsStorage {rftoolsstorage@1.15-1.1.4-beta DONE}
		rftoolscontrol-1.15-3.0.2-beta.jar RFToolsControl {rftoolscontrol@1.15-3.0.2-beta DONE}
		mapperbase-1.15.2-1.1.1.0.jar Mapper Base {mapperbase@1.15.2-1.1.1.0 DONE}
		embellishcraft-1.15.2-2.2.1.0.jar EmbellishCraft {embellishcraft@1.15.2-2.2.1.0 DONE}
		trash-1.15.2-0.1.4.jar Trash {trash@1.15.2-0.1.4 DONE}
		ToastControl-1.15.2-3.0.1.jar Toast Control {toastcontrol@3.0.1 DONE}
		JEITweaker-1.0.1.jar JEI Tweaker {jeitweaker@1.0.1 DONE}
		mininggadgets-1.3.5.jar Mining Gadgets {mininggadgets@1.3.5 DONE}
		EnderStorage-1.15.2-2.5.0.143-universal.jar EnderStorage {enderstorage@2.5.0.143 DONE}
		CraftTweaker-1.15.2-6.0.0.31.jar CraftTweaker {crafttweaker@6.0.0.31 DONE}
		rftoolspower-1.15-2.1.1-beta.jar RFToolsPower {rftoolspower@1.15-2.1.1-beta DONE}
		extradisks-1.15.2-1.2.2.jar Extra Disks {extradisks@1.15.2-1.2.2 DONE}
		Swamp-Expansion-1.15.2-1.7.2.jar Swamp Expansion {swampexpansion@NONE DONE}
		forge-1.15.2-31.2.30-universal.jar Forge {forge@31.2.30 DONE}
		Bountiful-1.15.2-3.1.2.jar Bountiful {bountiful@1.15.2-3.1.2 DONE}
		ironchest-1.15.2-10.0.3.jar Iron Chests {ironchest@1.15.2-10.0.1 DONE}
		CraftingTweaks_1.15.2-11.0.1.jar Crafting Tweaks {craftingtweaks@11.0.1 DONE}
		forge-1.15.2-31.2.30-server.jar Minecraft {minecraft@1.15.2 DONE}
		cofh_core-1.15.2-0.4.0b.jar CoFH Core {cofh_core@0.4.0b DONE}
		ensorcellation-1.15.2-0.4.1b.jar Ensorcellation {ensorcellation@0.4.1b DONE}
		The-Endergetic-Expansion-1.15.2-v1.3.2.jar The Endergetic Expansion {endergetic@1.3.2 DONE}
		rftoolsutility-1.15-2.1.3-beta.jar RFToolsUtility {rftoolsutility@1.15-2.1.3-beta DONE}
		swingthroughgrass-1.15.2-1.4.0.jar SwingThroughGrass {swingthroughgrass@1.15.2-1.4.0 DONE}
		ToolBelt-1.15.2-1.14.1.jar Tool Belt {toolbelt@1.14.1 DONE}
		titanium-1.15.2-2.4.2.jar Titanium {titanium@2.4.2 DONE}
		Psi r1.2-82.jar Psi {psi@r1.2-80 DONE}
		ImmersiveEngineering-0.15-103.jar Immersive Engineering {immersiveengineering@0.15-101 DONE}
		SilentLib-1.15.2-4.6.4+56.jar Silent Lib {silentlib@4.6.4+56 DONE}
		forbidden_arcanus-1.15.2-1.4.jar Forbidden & Arcanus {forbidden_arcanus@1.15.2-1.4 DONE}
		archers_paradox-1.15.2-0.4.0b.jar Archer's Paradox {archers_paradox@0.4.0b DONE}
		Atmospheric-1.15.2-1.4.1.jar Atmospheric {atmospheric@1.4.1 DONE}
		rftoolsbuilder-1.15-2.1.3-beta.jar RFToolsBuilder {rftoolsbuilder@1.15-2.1.3-beta DONE}
		paintings-1.15.2-7.0.0.0.jar Paintings ++ {paintings@1.14.4-6.0.1.5 DONE}
		Xaeros_Minimap_20.15.0_Forge_1.15.2.jar Xaero's Minimap {xaerominimap@20.15.0 DONE}
		JAOPCA-1.15.2-3.2.0.11.jar JAOPCA {jaopca@3.2.0.11 DONE}
		ftb-backups-2.1.0.1.jar FTB Utilities: Backups {ftbbackups@2.1.0.1 DONE}
		serverconfigupdater-1.1.jar ServerConfig Updater {serverconfigupdater@1.1 DONE}
		FastWorkbench-1.15.1-3.0.0.jar FastWorkbench {fastbench@3.0.0 DONE}
		autumnity-1.3.2-1.15.2.jar Autumnity {autumnity@1.3.2 DONE}
		polymorph-FORGE-1.15.2-0.3.jar Polymorph {polymorph@FORGE-1.15.2-0.3 DONE}
		AutoRegLib-1.5-40.jar AutoRegLib {autoreglib@1.5-40 DONE}
		AkashicTome-1.3-13.jar Akashic Tome {akashictome@1.3-13 DONE}
		Quark-r2.1-245.jar Quark {quark@r2.1-245 DONE}
		StorageDrawers-1.15.2-7.0.2.jar Storage Drawers {storagedrawers@1.15.2-7.0.1 DONE}
		FluxNetworks-1.15.2-5.0.3-4.jar Flux Networks {fluxnetworks@1.15.2-5.0.3-4 DONE}
		DoubleSlabs-1.15-2.7.6.jar Double Slabs {doubleslabs@2.7.6 DONE}
		themidnight-0.5.9.jar The Midnight {midnight@0.5.9 DONE}
		structurize-0.13.4-ALPHA.jar Structurize {structurize@0.13.4-ALPHA DONE}
		minecolonies-0.13.18-ALPHA-universal.jar Minecolonies {minecolonies@0.13.18-ALPHA DONE}
		FastFurnace-1.15.1-3.0.0.jar FastFurnace {fastfurnace@3.0.0 DONE}
		AppleSkin-mc1.15.2-forge-1.0.14.jar AppleSkin {appleskin@1.0.14 DONE}
		engineersdecor-1.15.2-1.1.0.jar Engineer's Decor {engineersdecor@1.1.0 DONE}
		Aquaculture-1.15.2-2.0.16.jar Aquaculture 2 {aquaculture@1.15.2-2.0.16 DONE}
		refinedstorageaddons-0.6.2.jar Refined Storage Addons {refinedstorageaddons@0.6.2 DONE}
		CosmeticArmorReworked-1.15.2-v3a.jar CosmeticArmorReworked {cosmeticarmorreworked@1.15.2-v3a DONE}
		overloadedarmorbar-4.0.0.jar Overloaded Armor Bar {overloadedarmorbar@4.0.0 DONE}
		OpenLoader-1.15.2-4.0.5.jar OpenLoader {openloader@4.0.5 DONE}
		xptome-1.15.2-v1.1.5.jar XP Tome {xpbook@v1.1.5 DONE}
	Kiwi Modules: 
		fruittrees:cherry
		fruittrees:fruittrees
		fruittrees:hybridization
		kiwi:contributors
		kiwi:data
	[Psi] Active spell: None
	Player Count: 0 / 100; []
	Data Packs: mod:scenic, mod:structure_gel, mod:packmenu (incompatible), mod:toughnessbar (incompatible), mod:servertabinfo (incompatible), mod:betteradvancements (incompatible), mod:inventorysorter (incompatible), mod:druidcraft, mod:conjurer_illager, mod:snowundertrees (incompatible), mod:toastcontrol (incompatible), mod:jeitweaker, mod:crafttweaker (incompatible), mod:paintings (incompatible), mod:serverconfigupdater, mod:akashictome (incompatible), mod:engineersdecor, mod:openloader (incompatible), mod:xpbook (incompatible), vanilla, inmemory:jaopca (incompatible), mod:netherportalfix (incompatible), mod:aiotbotania, mod:refinedpipes, mod:doggytalents (incompatible), mod:mcwwindows, mod:silents_mechanisms (incompatible), mod:essentials (incompatible), mod:terraforged, mod:xaeroworldmap, mod:cookingforblockheads (incompatible), mod:placebo (incompatible), mod:powah (incompatible), mod:bookshelf (incompatible), mod:uteamcore, mod:randompatches (incompatible), mod:darkutils (incompatible), mod:apotheosis (incompatible), mod:progressivebosses, mod:mcwdoors, mod:mekanismgenerators, mod:absentbydesign (incompatible), mod:refinedstorage (incompatible), mod:mcwbridges, mod:lightestlamp, mod:industrialforegoing (incompatible), mod:usefulbackpacks, mod:torchmaster (incompatible), mod:embellishcraft (incompatible), mod:biomesoplenty, mod:phosphor, mod:mekanismadditions, mod:valhelsia_structures (incompatible), mod:lollipop (incompatible), mod:silentgear (incompatible), mod:simplefarming, mod:solarflux (incompatible), mod:curios (incompatible), mod:botania (incompatible), mod:patchouli (incompatible), mod:extlights, mod:cloth-config2 (incompatible), mod:libnonymous (incompatible), mod:elevatorid, mod:mekanismtools, mod:mcwroofs, mod:cfm (incompatible), mod:curiouselytra (incompatible), mod:aiimprovements (incompatible), mod:mcwfurnitures, mod:bwncr (incompatible), mod:fastleafdecay, mod:codechickenlib (incompatible), mod:leavesdecayonotherleaves, mod:quarkoddities, mod:trashslot (incompatible), mod:torchslabmod, mod:mining_helmet (incompatible), mod:jei (incompatible), mod:attributefix (incompatible), mod:abnormals_core, mod:buzzierbees, mod:mekanism, mod:caelus (incompatible), mod:upgrade_aquatic (incompatible), mod:reap, mod:create, mod:waystones (incompatible), mod:clumps (incompatible), mod:comforts (incompatible), mod:naturescompass (incompatible), mod:fruittrees, mod:kiwi, mod:storagenetwork (incompatible), mod:sereneseasons, mod:decorative_blocks, mod:botanypots (incompatible), mod:curioofundying (incompatible), mod:endergetic (incompatible), mod:bonsaitrees2, mod:mcjtylib (incompatible), mod:rftoolsbase (incompatible), mod:xnet (incompatible), mod:rftoolsstorage (incompatible), mod:rftoolscontrol (incompatible), mod:mapperbase, mod:trash, mod:mininggadgets (incompatible), mod:enderstorage (incompatible), mod:rftoolspower (incompatible), mod:extradisks, mod:swampexpansion (incompatible), mod:forge (incompatible), mod:bountiful (incompatible), mod:ironchest, mod:craftingtweaks (incompatible), mod:cofh_core (incompatible), mod:ensorcellation (incompatible), mod:rftoolsutility (incompatible), mod:swingthroughgrass (incompatible), mod:toolbelt (incompatible), mod:titanium (incompatible), mod:psi (incompatible), mod:immersiveengineering (incompatible), mod:silentlib (incompatible), mod:forbidden_arcanus, mod:archers_paradox (incompatible), mod:atmospheric, mod:rftoolsbuilder (incompatible), mod:xaerominimap, mod:jaopca (incompatible), mod:ftbbackups (incompatible), mod:fastbench (incompatible), mod:autumnity, mod:polymorph, mod:autoreglib (incompatible), mod:quark, mod:storagedrawers (incompatible), mod:fluxnetworks, mod:doubleslabs, mod:midnight, mod:structurize (incompatible), mod:minecolonies (incompatible), mod:fastfurnace (incompatible), mod:appleskin (incompatible), mod:aquaculture, mod:refinedstorageaddons (incompatible), mod:cosmeticarmorreworked (incompatible), mod:overloadedarmorbar (incompatible), openloader/Valhelsia-Recipes, openloader/Valhelsia-SilentGear, file/LoveVNDev.zip
	Is Modded: Definitely; Server brand changed to 'forge'
	Type: Dedicated Server (map_server.txt)
```

**Comment by ChloeDawn** [comment]
I see now. Forge makes `Block#getItem` server-accessible at runtime. But doesn't account for the banner block's override in 1.15. In 1.16 it is partially accounting for it now, making `BannerTileEntity#getItem` server-accessible - but it still is not accounting for `BannerBlock#forColor` so it will crash in both versions still. This is something that needs to be fixed on Forge's end.
