### ISSUE TITLE
quando entro no minecraft da este problema

### ISSUE THREAD

**Issue by diogos1708** [McJtyMods/RFToolsBuilder#78]
---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 06-01-2022 6:00
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.fml.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:85) [?:?] {re:classloading}
	at net.minecraftforge.fml.client.ClientModLoader.completeModLoading(ClientModLoader.java:188) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$null$1(Minecraft.java:508) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft$$Lambda$6981/891130813.run(Unknown Source) [?:?] {}
	at net.minecraft.util.Util.func_215077_a(Util.java:430) [?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.lambda$new$2(Minecraft.java:504) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft$$Lambda$6764/1765747849.accept(Unknown Source) [?:?] {}
	at net.minecraft.client.gui.ResourceLoadProgressGui.func_230430_a_(ResourceLoadProgressGui.java:172) [?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:802) [?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:977) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.2.22.jar:36.2] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$495/1980560788.call(Unknown Source) [forge-1.16.5-36.2.22.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.lang.ClassLoader.findClass(ClassLoader.java:530) ~[?:1.8.0_51] {}
-- MOD rftoolsbuilder --
Details:
	Caused by 0: java.lang.IllegalAccessError: no such method: mcjty.rftoolsbuilder.modules.builder.blocks.BuilderTileEntity.createBlock()BaseBlock/invokeStatic
		at java.lang.invoke.MethodHandleNatives.linkMethodHandleConstant(MethodHandleNatives.java:483) ~[?:1.8.0_51] {}
		at mcjty.rftoolsbuilder.modules.builder.BuilderModule.<clinit>(BuilderModule.java:50) ~[?:1.16-3.1.2] {re:classloading}
		at mcjty.rftoolsbuilder.RFToolsBuilder.setupModules(RFToolsBuilder.java:44) ~[?:1.16-3.1.2] {re:classloading}
		at mcjty.rftoolsbuilder.RFToolsBuilder.<init>(RFToolsBuilder.java:28) ~[?:1.16-3.1.2] {re:classloading}
		at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_51] {}
		at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_51] {}
		at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_51] {}
		at java.lang.reflect.Constructor.newInstance(Constructor.java:422) ~[?:1.8.0_51] {}
		at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_51] {}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:81) ~[?:36.2] {re:classloading}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer$$Lambda$3083/1384626783.run(Unknown Source) ~[?:?] {}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[?:?] {re:classloading}
		at net.minecraftforge.fml.ModContainer$$Lambda$3201/757298272.run(Unknown Source) ~[?:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1618) ~[?:1.8.0_51] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1610) ~[?:1.8.0_51] {}
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_51] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_51] {}
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) ~[?:1.8.0_51] {re:computing_frames}
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_51] {}

	Caused by 1: java.lang.NoClassDefFoundError: mcjty/lib/container/NoDirectionItemHander
		at java.lang.invoke.MethodHandleNatives.resolve(Native Method) ~[?:1.8.0_51] {}
		at java.lang.invoke.MemberName$Factory.resolve(MemberName.java:962) ~[?:1.8.0_51] {}
		at java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:987) ~[?:1.8.0_51] {}
		at java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:1390) ~[?:1.8.0_51] {}
		at java.lang.invoke.MethodHandles$Lookup.linkMethodHandleConstant(MethodHandles.java:1746) ~[?:1.8.0_51] {}
		at java.lang.invoke.MethodHandleNatives.linkMethodHandleConstant(MethodHandleNatives.java:477) ~[?:1.8.0_51] {}
		at mcjty.rftoolsbuilder.modules.builder.BuilderModule.<clinit>(BuilderModule.java:50) ~[?:1.16-3.1.2] {re:classloading}
		at mcjty.rftoolsbuilder.RFToolsBuilder.setupModules(RFToolsBuilder.java:44) ~[?:1.16-3.1.2] {re:classloading}
		at mcjty.rftoolsbuilder.RFToolsBuilder.<init>(RFToolsBuilder.java:28) ~[?:1.16-3.1.2] {re:classloading}
		at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_51] {}
		at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_51] {}
		at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_51] {}
		at java.lang.reflect.Constructor.newInstance(Constructor.java:422) ~[?:1.8.0_51] {}
		at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_51] {}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:81) ~[?:36.2] {re:classloading}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer$$Lambda$3083/1384626783.run(Unknown Source) ~[?:?] {}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[?:?] {re:classloading}
		at net.minecraftforge.fml.ModContainer$$Lambda$3201/757298272.run(Unknown Source) ~[?:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1618) ~[?:1.8.0_51] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1610) ~[?:1.8.0_51] {}
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_51] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_51] {}
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) ~[?:1.8.0_51] {re:computing_frames}
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_51] {}

	Mod File: rftoolsbuilder-1.16-3.1.2.jar
	Failure message: RFToolsBuilder (rftoolsbuilder) has failed to load correctly
		java.lang.IllegalAccessError: no such method: mcjty.rftoolsbuilder.modules.builder.blocks.BuilderTileEntity.createBlock()BaseBlock/invokeStatic
	Mod Version: 1.16-3.1.2
	Mod Issue URL: http://github.com/McJtyMods/RFToolsBuilder/issues
	Exception message: java.lang.ClassNotFoundException: mcjty.lib.container.NoDirectionItemHander
Stacktrace:
	at java.lang.ClassLoader.findClass(ClassLoader.java:530) ~[?:1.8.0_51] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_51] {}
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:106) ~[modlauncher-8.0.9.jar:?] {re:classloading}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_51] {}
	at java.lang.invoke.MethodHandleNatives.resolve(Native Method) ~[?:1.8.0_51] {}
	at java.lang.invoke.MemberName$Factory.resolve(MemberName.java:962) ~[?:1.8.0_51] {}
	at java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:987) ~[?:1.8.0_51] {}
	at java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:1390) ~[?:1.8.0_51] {}
	at java.lang.invoke.MethodHandles$Lookup.linkMethodHandleConstant(MethodHandles.java:1746) ~[?:1.8.0_51] {}
	at java.lang.invoke.MethodHandleNatives.linkMethodHandleConstant(MethodHandleNatives.java:477) ~[?:1.8.0_51] {}
	at mcjty.rftoolsbuilder.modules.builder.BuilderModule.<clinit>(BuilderModule.java:50) ~[?:1.16-3.1.2] {re:classloading}
	at mcjty.rftoolsbuilder.RFToolsBuilder.setupModules(RFToolsBuilder.java:44) ~[?:1.16-3.1.2] {re:classloading}
	at mcjty.rftoolsbuilder.RFToolsBuilder.<init>(RFToolsBuilder.java:28) ~[?:1.16-3.1.2] {re:classloading}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_51] {}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422) ~[?:1.8.0_51] {}
	at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:81) ~[?:36.2] {re:classloading}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer$$Lambda$3083/1384626783.run(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModContainer$$Lambda$3201/757298272.run(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1618) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1610) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) ~[?:1.8.0_51] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_51] {}

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 5629614144 bytes (5368 MB) / 6140461056 bytes (5856 MB) up to 6140461056 bytes (5856 MB)
	CPUs: 4
	JVM Flags: 11 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -XX:+IgnoreUnrecognizedVMOptions -Xmn128M -Xmx5826M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 8.0.9+86+master.3cf110c
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.4.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.2.22.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.22.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.2.22.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.22.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.4.jar mixin TRANSFORMATIONSERVICE 
		/OptiFine-1.16.5_HD_U_G8_pre2.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.2.22.jar fml TRANSFORMATIONSERVICE 
	FML: 36.2
	Forge: net.minecraftforge:36.2.22
	FML Language Providers: 
		javafml@36.2
		minecraft@1
	Mod List: 
		rsrequestify-1.16.5-2.1.4.jar                     |RSRequestify                  |rsrequestify                  |2.1.4               |CREATE_REG|Manifest: NOSIGNATURE
		supermartijn642configlib-1.0.9-mc1.16.jar         |SuperMartijn642's Config Lib  |supermartijn642configlib      |1.0.9               |CREATE_REG|Manifest: NOSIGNATURE
		simplemagnets-1.1.2-mc1.16.5.jar                  |Simple Magnets                |simplemagnets                 |1.1.2               |CREATE_REG|Manifest: NOSIGNATURE
		jei-1.16.5-7.7.1.137.jar                          |Just Enough Items             |jei                           |7.7.1.137           |CREATE_REG|Manifest: NOSIGNATURE
		Mekanism-1.16.5-10.0.24.453.jar                   |Mekanism                      |mekanism                      |10.0.24             |CREATE_REG|Manifest: NOSIGNATURE
		journeymap-1.16.5-5.8.0beta2.jar                  |Journeymap                    |journeymap                    |5.8.0beta2          |CREATE_REG|Manifest: NOSIGNATURE
		TravelersBackpack-1.16.5-5.4.5.jar                |Traveler's Backpack           |travelersbackpack             |5.4.5               |CREATE_REG|Manifest: NOSIGNATURE
		NaturesCompass-1.16.5-1.9.1-forge.jar             |Nature's Compass              |naturescompass                |1.16.5-1.9.1-forge  |CREATE_REG|Manifest: NOSIGNATURE
		Bookshelf-Forge-1.16.5-10.3.29.jar                |Bookshelf                     |bookshelf                     |10.3.29             |CREATE_REG|Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		mcjtylib-1.16-5.1.2.jar                           |McJtyLib                      |mcjtylib                      |1.16-5.1.2          |CREATE_REG|Manifest: NOSIGNATURE
		rftoolsbase-1.16-2.1.1.jar                        |RFToolsBase                   |rftoolsbase                   |1.16-2.1.1          |CREATE_REG|Manifest: NOSIGNATURE
		DarkUtilities-1.16.5-8.0.11.jar                   |Dark Utilities                |darkutils                     |8.0.11              |CREATE_REG|Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		MekanismGenerators-1.16.5-10.0.24.453.jar         |Mekanism: Generators          |mekanismgenerators            |10.0.24             |CREATE_REG|Manifest: NOSIGNATURE
		FpsReducer-forge-1.24-mc1.16.5.jar                |FPS Reducer                   |fpsreducer                    |1.24-mc1.16.5       |CREATE_REG|Manifest: NOSIGNATURE
		rftoolspower-1.16-3.0.11.jar                      |RFToolsPower                  |rftoolspower                  |1.16-3.0.11         |CREATE_REG|Manifest: NOSIGNATURE
		forge-1.16.5-36.2.22-universal.jar                |Forge                         |forge                         |36.2.22             |CREATE_REG|Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		refinedstorage-1.9.16.jar                         |Refined Storage               |refinedstorage                |1.9.16              |CREATE_REG|Manifest: NOSIGNATURE
		ZeroCore2-1.16.5-2.1.7.jar                        |Zero CORE 2                   |zerocore                      |1.16.5-2.1.7        |CREATE_REG|Manifest: NOSIGNATURE
		forge-1.16.5-36.2.22-client.jar                   |Minecraft                     |minecraft                     |1.16.5              |CREATE_REG|Manifest: NOSIGNATURE
		TConstruct-1.16.5-3.3.0.308.jar                   |Tinkers' Construct            |tconstruct                    |3.3.0.308           |CREATE_REG|Manifest: NOSIGNATURE
		industrial-foregoing-1.16.5-3.2.14.7-16.jar       |Industrial Foregoing          |industrialforegoing           |3.2.14.7            |CREATE_REG|Manifest: NOSIGNATURE
		theoneprobe-1.16-3.1.4.jar                        |The One Probe                 |theoneprobe                   |1.16-3.1.4          |CREATE_REG|Manifest: NOSIGNATURE
		titanium-1.16.5-3.2.8.5-20.jar                    |Titanium                      |titanium                      |3.2.8.5             |CREATE_REG|Manifest: NOSIGNATURE
		Craftable+Elytras+Mod+1_16_x.jar                  |Craftable Elytras Mod         |bkcraftableelytra             |[1.16,)             |CREATE_REG|Manifest: NOSIGNATURE
		supermartijn642corelib-1.0.15-mc1.16.5.jar        |SuperMartijn642's Core Lib    |supermartijn642corelib        |1.0.15              |CREATE_REG|Manifest: NOSIGNATURE
		ChickenChunks-1.16.5-2.9.0.88-universal.jar       |ChickenChunks                 |chickenchunks                 |2.9.0.88            |CREATE_REG|Manifest: 31:e6:db:63:47:4a:6e:e0:0a:2c:11:d1:76:db:4e:82:ff:56:2d:29:93:d2:e5:02:bd:d3:bd:9d:27:47:a5:71
		craftable.jar                                     |Craftable Blaze Powder        |craftable_blaze_powder        |1.0.0               |CREATE_REG|Manifest: NOSIGNATURE
		rftoolsbuilder-1.16-3.1.2.jar                     |RFToolsBuilder                |rftoolsbuilder                |1.16-3.1.2          |ERROR     |Manifest: NOSIGNATURE
		curios-forge-1.16.5-4.0.5.3.jar                   |Curios API                    |curios                        |1.16.5-4.0.5.3      |CREATE_REG|Manifest: NOSIGNATURE
		Patchouli-1.16.4-53.2.jar                         |Patchouli                     |patchouli                     |1.16.4-53.2         |CREATE_REG|Manifest: NOSIGNATURE
		Mantle-1.16.5-1.6.147.jar                         |Mantle                        |mantle                        |1.6.147             |CREATE_REG|Manifest: NOSIGNATURE
		FluxNetworks-1.16.5-6.1.7.12.jar                  |Flux Networks                 |fluxnetworks                  |6.1.7.12            |CREATE_REG|Manifest: NOSIGNATURE
		Craftable+Ender+Pearl+v.1.1.jar                   |Craftable Ender Pearl         |craftable_ender_pearl         |1.0.0               |CREATE_REG|Manifest: NOSIGNATURE
		angel-ring-1.16.4-5-1.3.4.1.jar                   |Angel Ring                    |angelring                     |1.3.4.1             |CREATE_REG|Manifest: NOSIGNATURE
		CompactVoidMiners-B1.16.5-1.12.jar                |Compact Void Miners           |compactvoidminers             |1.16.5-1.12         |CREATE_REG|Manifest: NOSIGNATURE
		ftb-ultimine-forge-1605.3.0-build.33.jar          |FTB Ultimine                  |ftbultimine                   |1605.3.0-build.33   |CREATE_REG|Manifest: NOSIGNATURE
		Runelic-1.16.5-7.0.2.jar                          |Runelic                       |runelic                       |7.0.2               |CREATE_REG|Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		ExtraStorage-1.16.5-1.6.0.jar                     |Extra Storage                 |extrastorage                  |1.6.0               |CREATE_REG|Manifest: NOSIGNATURE
		MekanismTools-1.16.5-10.0.24.453.jar              |Mekanism: Tools               |mekanismtools                 |10.0.24             |CREATE_REG|Manifest: NOSIGNATURE
		constructionwand-1.16.5-2.5.jar                   |Construction Wand             |constructionwand              |1.16.5-2.5          |CREATE_REG|Manifest: NOSIGNATURE
		BetterFurnacesReforged-1.16.5-1.6.1.jar           |BetterFurnaces Reforged       |betterfurnacesreforged        |1.16.5-1.6.1        |CREATE_REG|Manifest: NOSIGNATURE
		architectury-1.26.38.jar                          |Architectury                  |architectury                  |1.26.38             |CREATE_REG|Manifest: NOSIGNATURE
		ftb-library-forge-1605.3.4-build.90.jar           |FTB Library                   |ftblibrary                    |1605.3.4-build.90   |CREATE_REG|Manifest: NOSIGNATURE
		ExtremeReactors2-1.16.5-2.0.33.jar                |Extreme Reactors              |bigreactors                   |1.16.5-2.0.33       |CREATE_REG|Manifest: NOSIGNATURE
		Easy+Diamond-1.16.5-1.2.0.jar                     |Easy Diamond                  |diamond                       |1.2.0               |CREATE_REG|Manifest: NOSIGNATURE
		refinedstorageaddons-0.7.4.jar                    |Refined Storage Addons        |refinedstorageaddons          |0.7.4               |CREATE_REG|Manifest: NOSIGNATURE
		toms_storage-1.2.19.jar                           |Tom's Simple Storage Mod      |toms_storage                  |1.2.19              |CREATE_REG|Manifest: NOSIGNATURE
		CodeChickenLib-1.16.5-4.0.5.438-universal.jar     |CodeChicken Lib               |codechickenlib                |4.0.5.438           |CREATE_REG|Manifest: 31:e6:db:63:47:4a:6e:e0:0a:2c:11:d1:76:db:4e:82:ff:56:2d:29:93:d2:e5:02:bd:d3:bd:9d:27:47:a5:71
		EnderStorage-1.16.5-2.8.0.168-universal.jar       |EnderStorage                  |enderstorage                  |2.8.0.168           |CREATE_REG|Manifest: 31:e6:db:63:47:4a:6e:e0:0a:2c:11:d1:76:db:4e:82:ff:56:2d:29:93:d2:e5:02:bd:d3:bd:9d:27:47:a5:71
		Cyclic-1.16.5-1.5.12.jar                          |Cyclic                        |cyclic                        |1.16.5-1.5.12       |CREATE_REG|Manifest: 1f:47:ac:b1:61:82:96:b8:47:19:16:d2:61:81:11:60:3a:06:4b:61:31:56:7d:44:31:1e:0c:6f:22:5b:4c:ed
	Crash Report UUID: 3279719e-86aa-4124-9730-a05dbc517eb1
	OptiFine Version: OptiFine_1.16.5_HD_U_G8_pre2
	OptiFine Build: 20210305-002749
	Render Distance Chunks: 6
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 - Build 30.0.100.9837
	OpenGlRenderer: Intel(R) UHD Graphics
	OpenGlVendor: Intel
	CpuCount: 4

**Comment by McJty** [comment]
You are missing McJtyLib
